### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by dpsanders** [REX-Computing/unumjl#7]
Once the change to Julia 0.4 has been made, it would be useful to start transitioning comments to new-style docstrings using Markdown. Trivial example:

``` julia
doc"""The function `f` multiplies its argument by 3.
It is otherwise pretty uninteresting."""
f(x) = 3x
```

EDIT:
Then doing `?f` from the REPL gives

``` julia
help?> f
search: f fd for fma fld fft full find filt fill fft! fdio frexp foldr foldl

  The function f multiplies its argument by 3. It is otherwise pretty
  uninteresting.
```

**Comment by ityonemo** [comment]
process has begun; many major functions have been docstring'd.
