### ISSUE TITLE
unum(1)  <  ( unum(2) / unum(3)  )

### ISSUE THREAD

**Issue by JeffreySarnoff** [REX-Computing/unumjl#8]
unum1 = convert(Unum{4,5}, 1.0);  #  Float64(calculate(unum1)) == 1.0
unum2 = convert(Unum{4,5}, 2.0);  #  Float64(calculate(unum2)) == 2.0
unum3 = convert(Unum{4,5}, 3.0);  #  Float64(calculate(unum3)) == 3.0
twothirds = unum2 / unum3; 
twothirds > unum1
true

twothirds
Unums.Unum{4,5}(0x001f,0x0001,0x0001,0x3fffffff00000000,0x0000000000000001)
calculate(ans) 
1.24999999976716935634613037109375

**Comment by ityonemo** [comment]
Fixed in updated "directory-reorg".

**Comment by JeffreySarnoff** [comment]
congratulations
